version: "2"
services:
  php:
    image: app-backend_app
    ports:
      - "4000:80"
    environment:
      DB_HOST: mysql
      DB_USERNAME: forus
      DB_DATABASE: forus.io
      DB_PASSWORD: JkNvw4m9juFEy5gxrSVcRXgzUHS7ZzcG
    command: bash -c "cd ./_docker && ./wait-for-mysql.sh && cd ../ && php artisan migrate:refresh --seed && apache2-foreground"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: JkNvw4m9juFEy5gxrSVcRXgzUHS7ZzcG
      MYSQL_DATABASE: forus.io
      MYSQL_USER: forus
      MYSQL_PASSWORD: JkNvw4m9juFEy5gxrSVcRXgzUHS7ZzcG